### PR TITLE
can login as company

### PR DESCRIPTION
**Pull request by beppek**

### CODE REVIEW

**Review by ntwigs — APPROVED** [review]
Hittar inget knasigt! Go for it 🚀

**Comment by ntwigs** [comment]
Åh! Kom på att du kan fixa till company auth i readme också!

**Comment by beppek** [comment]
Uppdaterat readme

**Review by ntwigs — APPROVED** [review]
Merge on! :rocket: Noticed that all the links are http and not https - but it redirects, so no harm done! :smile:

**Pull request merged**
